#ifndef BOSONO_BOSONO_H
#define BOSONO_BOSONO_H

#define BOSONOGA_EXIT_SUCCESS 0
#define BOSONOGA_EXIT_FAILURE 1

#define BOSONO_LIMIT 16777216
#define BOSONO_TOKEN_LIMIT 2621440
#define BOSONO_STRING_MAX_BYTES 4095
#define BOSONO_STRING_LIMIT (BOSONO_STRING_MAX_BYTES + 1)
#define BOSONO_RULE_LIMIT 72
#define BOSONO_RULE_INFO_LIMIT 224
#define BOSONO_THEME_MIN 1
#define BOSONO_THEME_LIMIT 8
#define BOSONO_THEME_NAME_LIMIT 64
#define BOSONO_THEME_COLOR_COUNT 3
#define BOSONO_ASSET_LIMIT (BOSONO_THEME_LIMIT * BOSONO_THEME_COLOR_COUNT)
#define BOSONO_ASSET_PATH_LIMIT 128
#define BOSONO_VARIABLE_BYTES (120U * 1024U * 1024U)
#define BOSONO_VARIABLE_NAME_LIMIT 64
#define BOSONO_CONDITION_DEPTH_LIMIT 32

#define BOSONO_TEXT_(value) #value
#define BOSONO_TEXT(value) BOSONO_TEXT_(value)

#endif
