#ifndef BOSONO_BOSONO_H
#define BOSONO_BOSONO_H

#define BOSONO_LIMIT 67108864
#define BOSONO_TOKEN_LIMIT 8388608
#define BOSONO_STRING_MAX_BYTES 4095
#define BOSONO_STRING_LIMIT (BOSONO_STRING_MAX_BYTES + 1)
#define BOSONO_RULE_LIMIT 72
#define BOSONO_RULE_INFO_LIMIT 224
#define BOSONO_THEME_LIMIT 4
#define BOSONO_THEME_NAME_LIMIT 64
#define BOSONO_THEME_COLOR_COUNT 3

#define BOSONO_TEXT_(value) #value
#define BOSONO_TEXT(value) BOSONO_TEXT_(value)

#endif
